### ISSUE TITLE
Laggy (Low FPS?) Front Camera

### ISSUE THREAD

**Issue by bluewingtitan** [marblear/issues#19]
Version: 1.28 (Current Store-Build)
Tester described following bug: "The front camera looked a bit lagging in my device (Oneplus Nord) if that could be optimized a bit, it'd be great."

**Comment by derwaldgeist** [comment]
Interesting. I would the front-camera expect to be *less* lagging, since all Marbles are deactivated once the user switches into selfie mode. Unfortunately, I don't see much we can do about this, because the camera is fully controlled by AR Core. Does this only happen during recording, or is it generally lagging?
